### ISSUE TITLE
segfault when ctrl-c with SyslogLogger registered

### ISSUE THREAD

**Issue by WebFreak001** [vibe-d/vibe.d#1884]
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000ae25cb in std.format.__T10FormatSpecTaZ.FormatSpec.fillUp() (this=...) at /usr/include/dmd/phobos/std/format.d:1155
1155        private void fillUp()
(gdb) bt
#0  0x0000000000ae25cb in std.format.__T10FormatSpecTaZ.FormatSpec.fillUp() (this=...) at /usr/include/dmd/phobos/std/format.d:1155
#1  0x0000000000ae59ee in std.format.__T10FormatSpecTaZ.FormatSpec.__T17writeUpToNextSpecTS3std5array17__T8AppenderTAyaZ8AppenderZ.writeUpToNextSpec() (this=..., writer=...) at /usr/include/dmd/phobos/std/format.d:1109
#2  0x0000000000ce3154 in std.format.__T14formattedWriteTS3std5array17__T8AppenderTAyaZ8AppenderTaTiZ.formattedWrite() (_param_2=9566120, fmt=..., w=...) at /usr/include/dmd/phobos/std/format.d:472
#3  0x0000000000d9041f in std.format.__T6formatTaTiZ.format() (_param_1=9566120, fmt=...) at /usr/include/dmd/phobos/std/format.d:5524
#4  0x0000000000e5c1f9 in std.datetime.fracSecsToISOString() ()
#5  0x0000000000e56fcb in std.datetime.SysTime.toISOExtString() ()
#6  0x0000000000dc5471 in vibe.core.log.SyslogLogger.beginLine() (this=0x7ffff3f0f600, msg=...) at ../vibe.d/core/vibe/core/log.d:600
#7  0x0000000000dc5c71 in vibe.core.log.LogOutputRange.__ctor() (this=..., level=<incomplete type>, line=1463, file=..., logger=...) at ../vibe.d/core/vibe/core/log.d:774
#8  0x0000000000dc9331 in vibe.core.log.__T3logVE4vibe4core3log8LogLeveli2VAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.log() (_param_1=0x0000000000dc924000007fffff7ffa90, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:124
#9  0x0000000000dc923d in vibe.core.log.__T8logDebugVAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.logDebug() (_param_1=0x0000000000da7b2400007ffff7ee3d00, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:135
#10 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#11 0x0000000000e0251f in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#12 0x0000000000e02500 in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#13 0x0000000000dbac18 in vibe.core.drivers.threadedfile.ThreadedFileStream.write() (this=0x7ffff3ed3880, _param_1=<incomplete type>, bytes_=...) at ../vibe.d/core/vibe/core/drivers/threadedfile.d:206
#14 0x0000000000dd99a7 in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:136
#15 0x0000000000dd9a0d in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:138
#16 0x0000000000dc5625 in vibe.core.log.SyslogLogger.beginLine() (this=0x7ffff3f0f600, msg=...) at ../vibe.d/core/vibe/core/log.d:631
#17 0x0000000000dc5c71 in vibe.core.log.LogOutputRange.__ctor() (this=..., level=<incomplete type>, line=1463, file=..., logger=...) at ../vibe.d/core/vibe/core/log.d:774
#18 0x0000000000dc9331 in vibe.core.log.__T3logVE4vibe4core3log8LogLeveli2VAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.log() (_param_1=0x0000000000dc924000007fffff7fffb0, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:124
#19 0x0000000000dc923d in vibe.core.log.__T8logDebugVAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.logDebug() (_param_1=0x0000000000da7b2400007ffff7ee3d00, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:135
#20 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#21 0x0000000000e0251f in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#22 0x0000000000e02500 in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#23 0x0000000000dbac18 in vibe.core.drivers.threadedfile.ThreadedFileStream.write() (this=0x7ffff3ed3880, _param_1=<incomplete type>, bytes_=...) at ../vibe.d/core/vibe/core/drivers/threadedfile.d:206
#24 0x0000000000dd99a7 in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:136
#25 0x0000000000dd9a0d in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:138
#26 0x0000000000dc5625 in vibe.core.log.SyslogLogger.beginLine() (this=0x7ffff3f0f600, msg=...) at ../vibe.d/core/vibe/core/log.d:631
#27 0x0000000000dc5c71 in vibe.core.log.LogOutputRange.__ctor() (this=..., level=<incomplete type>, line=1463, file=..., logger=...) at ../vibe.d/core/vibe/core/log.d:774
#28 0x0000000000dc9331 in vibe.core.log.__T3logVE4vibe4core3log8LogLeveli2VAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.log() (_param_1=0x0000000000dc924000007fffff8004d0, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:124
#29 0x0000000000dc923d in vibe.core.log.__T8logDebugVAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.logDebug() (_param_1=0x0000000000da7b2400007ffff7ee3d00, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:135
#30 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#31 0x0000000000e0251f in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#32 0x0000000000e02500 in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#33 0x0000000000dbac18 in vibe.core.drivers.threadedfile.ThreadedFileStream.write() (this=0x7ffff3ed3880, _param_1=<incomplete type>, bytes_=...) at ../vibe.d/core/vibe/core/drivers/threadedfile.d:206
#34 0x0000000000dd99a7 in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:136
#35 0x0000000000dd9a0d in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:138
#36 0x0000000000dc5625 in vibe.core.log.SyslogLogger.beginLine() (this=0x7ffff3f0f600, msg=...) at ../vibe.d/core/vibe/core/log.d:631
#37 0x0000000000dc5c71 in vibe.core.log.LogOutputRange.__ctor() (this=..., level=<incomplete type>, line=1463, file=..., logger=...) at ../vibe.d/core/vibe/core/log.d:774
#38 0x0000000000dc9331 in vibe.core.log.__T3logVE4vibe4core3log8LogLeveli2VAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.log() (_param_1=0x0000000000dc924000007fffff8009f0, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:124
#39 0x0000000000dc923d in vibe.core.log.__T8logDebugVAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.logDebug() (_param_1=0x0000000000da7b2400007ffff7ee3d00, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:135
#40 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#41 0x0000000000e0251f in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#42 0x0000000000e02500 in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#43 0x0000000000dbac18 in vibe.core.drivers.threadedfile.ThreadedFileStream.write() (this=0x7ffff3ed3880, _param_1=<incomplete type>, bytes_=...) at ../vibe.d/core/vibe/core/drivers/threadedfile.d:206
#44 0x0000000000dd99a7 in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:136
#45 0x0000000000dd9a0d in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:138
#46 0x0000000000dc5625 in vibe.core.log.SyslogLogger.beginLine() (this=0x7ffff3f0f600, msg=...) at ../vibe.d/core/vibe/core/log.d:631
#47 0x0000000000dc5c71 in vibe.core.log.LogOutputRange.__ctor() (this=..., level=<incomplete type>, line=1463, file=..., logger=...) at ../vibe.d/core/vibe/core/log.d:774
#48 0x0000000000dc9331 in vibe.core.log.__T3logVE4vibe4core3log8LogLeveli2VAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.log() (_param_1=0x0000000000dc924000007fffff800f10, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:124
#49 0x0000000000dc923d in vibe.core.log.__T8logDebugVAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.logDebug() (_param_1=0x0000000000da7b2400007ffff7ee3d00, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:135
#50 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#51 0x0000000000e0251f in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#52 0x0000000000e02500 in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#53 0x0000000000dbac18 in vibe.core.drivers.threadedfile.ThreadedFileStream.write() (this=0x7ffff3ed3880, _param_1=<incomplete type>, bytes_=...) at ../vibe.d/core/vibe/core/drivers/threadedfile.d:206
#54 0x0000000000dd99a7 in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:136
#55 0x0000000000dd9a0d in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:138

...

#63880 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#63881 0x0000000000e0251f in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#63882 0x0000000000e02500 in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#63883 0x0000000000dbac18 in vibe.core.drivers.threadedfile.ThreadedFileStream.write() (this=0x7ffff3ed3880, _param_1=<incomplete type>, bytes_=...) at ../vibe.d/core/vibe/core/drivers/threadedfile.d:206
#63884 0x0000000000dd99a7 in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:136
#63885 0x0000000000dd9a0d in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:138
#63886 0x0000000000dc5625 in vibe.core.log.SyslogLogger.beginLine() (this=0x7ffff3f0f600, msg=...) at ../vibe.d/core/vibe/core/log.d:631
#63887 0x0000000000dc5c71 in vibe.core.log.LogOutputRange.__ctor() (this=..., level=<incomplete type>, line=1463, file=..., logger=...) at ../vibe.d/core/vibe/core/log.d:774
#63888 0x0000000000dc9331 in vibe.core.log.__T3logVE4vibe4core3log8LogLeveli2VAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.log() (_param_1=0x0000000000dc924000007fffffffdd10, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:124
#63889 0x0000000000dc923d in vibe.core.log.__T8logDebugVAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.logDebug() (_param_1=0x0000000000da7b2400007ffff7ee3d00, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:135
#63890 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#63891 0x0000000000e0251f in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#63892 0x0000000000e02500 in vibe.core.core.yield() () at ../vibe.d/core/vibe/core/core.d:751
#63893 0x0000000000dbac18 in vibe.core.drivers.threadedfile.ThreadedFileStream.write() (this=0x7ffff3ed3880, _param_1=<incomplete type>, bytes_=...) at ../vibe.d/core/vibe/core/drivers/threadedfile.d:206
#63894 0x0000000000dd99a7 in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:136
#63895 0x0000000000dd9a0d in vibe.core.stream.OutputStream.write() (this=0x7ffff3ed3898, bytes=...) at ../vibe.d/core/vibe/core/stream.d:138
#63896 0x0000000000dc5625 in vibe.core.log.SyslogLogger.beginLine() (this=0x7ffff3f0f600, msg=...) at ../vibe.d/core/vibe/core/log.d:631
#63897 0x0000000000dc5c71 in vibe.core.log.LogOutputRange.__ctor() (this=..., level=<incomplete type>, line=1463, file=..., logger=...) at ../vibe.d/core/vibe/core/log.d:774
#63898 0x0000000000dc9331 in vibe.core.log.__T3logVE4vibe4core3log8LogLeveli2VAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.log() (_param_1=0x0000000000dc924000007fffffffe230, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:124
#63899 0x0000000000dc923d in vibe.core.log.__T8logDebugVAyaa31_2e2e2f766962652e642f636f72652f766962652f636f72652f636f72652e64Vii1463TAyaTbZ.logDebug() (_param_1=0x0000000000da7b2400007ffff7ee3d00, fmt=...)
    at ../vibe.d/core/vibe/core/log.d:135
#63900 0x0000000000da7ad4 in vibe.core.core.VibeDriverCore.notifyIdle() (this=0x7ffff7ee3d00) at ../vibe.d/core/vibe/core/core.d:1463
#63901 0x0000000000dac54c in vibe.core.drivers.libevent2.Libevent2Driver.runEventLoop() (this=0x7ffff7ee0600) at ../vibe.d/core/vibe/core/drivers/libevent2.d:212
#63902 0x0000000000da53d6 in vibe.core.core.runEventLoop() () at ../vibe.d/core/vibe/core/core.d:206
#63903 0x0000000000da524c in vibe.core.core.runApplication() (args_out=...) at ../vibe.d/core/vibe/core/core.d:113
#63904 0x0000000000c8b918 in D main () at ../vibe.d/core/vibe/appmain.d:44
#63905 0x0000000000e3c7a0 in rt.dmain2._d_run_main() ()
#63906 0x0000000000e3c6d0 in rt.dmain2._d_run_main() ()
#63907 0x0000000000e3c749 in rt.dmain2._d_run_main() ()
#63908 0x0000000000e3c6d0 in rt.dmain2._d_run_main() ()
#63909 0x0000000000e3c640 in _d_run_main ()
#63910 0x0000000000c8b93e in main ()
```

This happens under the same circumstances as #1883 (a while(true) sleep(10.seconds) task and a timer)

I couldn't reproduce it in a clean program, not even when trying to mimic the timers

**Comment by WebFreak001** [comment]
just closing this because I don't have any more data of this happening anymore
