### ISSUE TITLE
sigsegv trying to connect to MongoDB via TLS

### ISSUE THREAD

**Issue by ohninedotseven** [vibe-d/vibe.d#1954]
```Performing "debug" build using dmd for x86_64.
dauth 0.6.3: target for configuration "library" is up to date.
vibe-d:utils 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:data 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:core 0.8.2-alpha.2: target for configuration "libevent" is up to date.
vibe-d:crypto 0.8.2-alpha.2: target for configuration "library" is up to date.
diet-ng 1.4.3: target for configuration "library" is up to date.
vibe-d:stream 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:textfilter 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:inet 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:tls 0.8.2-alpha.2: target for configuration "openssl" is up to date.
vibe-d:http 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:mail 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:mongodb 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:redis 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:web 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d 0.8.2-alpha.2: target for configuration "libevent" is up to date.
school-stuff-server ~master: building configuration "application"...
Compiling Diet HTML template main.dt...
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.getJob as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.getJob as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.getUser as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postLogin as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postNewAcc as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postNewJob as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postSale as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postClockIn as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postClockOut as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.logged_in as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.job_id as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.res as @safe.
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./school-stuff-server 
[warn] Unable to parse nameserver address fe80::b2b9:8aff:fe65:66d4%enp0s25
Listening for requests on http://127.0.0.1:8080/
censored.documents.azure.com
10255
Program exited with code -11
```

attaching GDB and running it gives me this backtrace
```Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b9b81c in SSL_CTX_set_cipher_list () from /usr/lib/libssl.so.1.1
(gdb) bt
#0  0x00007ffff7b9b81c in SSL_CTX_set_cipher_list () from /usr/lib/libssl.so.1.1
#1  0x0000555555d2b598 in vibe.stream.openssl.OpenSSLContext.setCipherList(immutable(char)[]) (
    this=0x7ffff7ec8500, list=...)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/tls/vibe/stream/openssl.d:683
#2  0x0000555555d2aa60 in vibe.stream.openssl.OpenSSLContext.this(vibe.stream.tls.TLSContextKind, vibe.stream.tls.TLSVersion) (this=0x7ffff7ec8500, ver=<incomplete type>, kind=<incomplete type>)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/tls/vibe/stream/openssl.d:501
#3  0x0000555555d37518 in vibe.stream.tls.createTLSContext(vibe.stream.tls.TLSContextKind, vibe.stream.tls.TLSVersion).createOpenSSLContext(vibe.stream.tls.TLSContextKind, vibe.stream.tls.TLSVersion) (
    ver=<incomplete type>, kind=<incomplete type>)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/tls/vibe/stream/tls.d:96
#4  0x0000555555d374e9 in vibe.stream.tls.createTLSContext(vibe.stream.tls.TLSContextKind, vibe.stream.tls.TLSVersion) (ver=<incomplete type>, kind=<incomplete type>)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/tls/vibe/stream/tls.d:109
#5  0x0000555555bec8b5 in vibe.db.mongo.connection.MongoConnection.connect() (this=0x7ffff7ed0e00)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/mongodb/vibe/db/mongo/connection.d:161
#6  0x0000555555be99fc in vibe.db.mongo.client.MongoClient.this(vibe.db.mongo.settings.MongoClientSettings).__lambda2() (this=0x7ffff7ec5550)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/mongodb/vibe/db/mongo/client.d:76
#7  0x0000555555bea03b in vibe.core.connectionpool.ConnectionPool!(vibe.db.mongo.connection.MongoConnection).ConnectionPool.lockConnection() (this=0x7ffff7ec8480, __HID4=0x7fffffffe068)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/core/vibe/core/connectionpool.d:94
#8  0x0000555555be9b8f in vibe.db.mongo.client.MongoClient.lockConnection() (this=0x7ffff7ec64c0, 
    __HID3=0x7fffffffe0e8)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/mongodb/vibe/db/mongo/client.d:152
#9  0x0000555555be9988 in vibe.db.mongo.client.MongoClient.this(vibe.db.mongo.settings.MongoClientSettings) (this=0x7ffff7ec64c0, settings=0x7ffff7ed2100)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/mongodb/vibe/db/mongo/client.d:81
#10 0x0000555555bf90b4 in vibe.db.mongo.mongo.connectMongoDB(vibe.db.mongo.settings.MongoClientSettings) (settings=0x7ffff7ed2100)
    at ../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/mongodb/vibe/db/mongo/mongo.d:95
#11 0x0000555555b50ad2 in D main () at source/app.d:361
(gdb) 
```

i've tried downgrading to 0.8.0, replacing the openssl lib, using LD_PRELOAD to load libssl.so.1.0, libssl3.so, etc. none have worked. my code is here: 
```d
        MongoClientSettings cfg;
	cfg = MongoClientSettings.init;
	parseMongoDBUrl(cfg, "mongodb://username:password@censored.documents.azure.com:10255/?ssl=true");
	writeln(cfg.hosts[0].name);
	writeln(cfg.hosts[0].port);

	client = connectMongoDB(cfg);	
```

if it helps, i'm running arch linux, installed openssl version is openssl 1.1.0.f-2, 
uname -a: `Linux thousands 4.13.7-1-ARCH #1 SMP PREEMPT Sat Oct 14 20:13:26 CEST 2017 x86_64 GNU/Linux
`
dub.selections.json is 
```json 
{
	"fileVersion": 1,
	"versions": {
		"botan": "1.12.9",
		"botan-math": "1.0.3",
		"dauth": "0.6.3",
		"diet-ng": "1.4.3",
		"eventcore": "0.8.20",
		"libasync": "0.8.3",
		"libevent": "2.0.2+2.0.16",
		"memutils": "0.4.9",
		"openssl": "1.1.5+1.0.1g",
		"taggedalgebraic": "0.10.7",
		"vibe-core": "1.2.1-alpha.2",
		"vibe-d": "0.8.2-alpha.2"
	}
}
```
i'm thinking it could be a version mismatch because the installed version is 1.1.0.f-2 while the one selecetd is 1.1.5+1.0.1g, and i'll go try downgrading it in the selections to the system version to go see if that fixes that. idk, however, and i'm sorta at a loss, blah.

**Comment by ohninedotseven** [comment]
oh and i've tried using vibe-d:tls with botan enabled or disabled. the crash i get with botan enabled is this:
```
Running pre-generate commands for botan...
Notice: Botan uses many symbols. Look into switching from ld (bfd) to ld (Gold) linker to reduce link times from >15s to <2s
Performing "debug" build using dmd for x86_64.
dauth 0.6.3: target for configuration "library" is up to date.
vibe-d:utils 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:data 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:core 0.8.2-alpha.2: target for configuration "libevent" is up to date.
vibe-d:crypto 0.8.2-alpha.2: target for configuration "library" is up to date.
diet-ng 1.4.3: target for configuration "library" is up to date.
vibe-d:stream 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:textfilter 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:inet 0.8.2-alpha.2: target for configuration "library" is up to date.
botan-math 1.0.3: target for configuration "regular" is up to date.
memutils 0.4.9: target for configuration "secure" is up to date.
botan 1.12.9: target for configuration "full" is up to date.
vibe-d:tls 0.8.2-alpha.2: target for configuration "botan" is up to date.
vibe-d:http 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:mail 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:mongodb 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:redis 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d:web 0.8.2-alpha.2: target for configuration "library" is up to date.
vibe-d 0.8.2-alpha.2: target for configuration "libevent" is up to date.
school-stuff-server ~master: building configuration "application"...
Compiling Diet HTML template main.dt...
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.getJob as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.getJob as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.getUser as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postLogin as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postNewAcc as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postNewJob as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postSale as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postClockIn as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.postClockOut as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.logged_in as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.job_id as @safe.
Non-@safe methods are deprecated in REST interfaces - Mark LibraryAPIImplem.res as @safe.
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./school-stuff-server 
[warn] Unable to parse nameserver address fe80::b2b9:8aff:fe65:66d4%enp0s25
Listening for requests on http://127.0.0.1:8080/
censored.documents.azure.com
10255
core.exception.AssertError@../../.dub/packages/vibe-d-0.8.2-alpha.2/vibe-d/core/vibe/core/net.d(210): port() called for invalid address family.
----------------
??:? _d_assert_msg [0x224481de]
??:? const pure nothrow @property @safe ushort vibe.core.net.NetworkAddress.port() [0x223d7e08]
??:? @trusted vibe.stream.botan.BotanTLSStream vibe.stream.botan.BotanTLSStream.__ctor(vibe.core.stream.Stream, vibe.stream.botan.BotanTLSContext, vibe.stream.tls.TLSStreamState, immutable(char)[], vibe.core.net.NetworkAddress) [0x22079dd7]
??:? @safe vibe.stream.tls.TLSStream vibe.stream.botan.BotanTLSContext.createStream(vibe.core.stream.Stream, vibe.stream.tls.TLSStreamState, immutable(char)[], vibe.core.net.NetworkAddress) [0x2207b5d5]
??:? @safe vibe.stream.tls.TLSStream vibe.stream.tls.createTLSStream!(vibe.core.net.TCPConnection).createTLSStream(vibe.core.net.TCPConnection, vibe.stream.tls.TLSContext, vibe.stream.tls.TLSStreamState, immutable(char)[], vibe.core.net.NetworkAddress) [0x21f421a9]
??:? @safe vibe.stream.tls.TLSStream vibe.stream.tls.createTLSStream!(vibe.core.net.TCPConnection).createTLSStream(vibe.core.net.TCPConnection, vibe.stream.tls.TLSContext, immutable(char)[], vibe.core.net.NetworkAddress) [0x21f42144]
??:? @safe void vibe.db.mongo.connection.MongoConnection.connect() [0x21f3d4eb]
??:? @safe vibe.db.mongo.connection.MongoConnection vibe.db.mongo.client.MongoClient.__ctor(vibe.db.mongo.settings.MongoClientSettings).__lambda2() [0x21f3a4db]
??:? @safe vibe.core.connectionpool.LockedConnection!(vibe.db.mongo.connection.MongoConnection).LockedConnection vibe.core.connectionpool.ConnectionPool!(vibe.db.mongo.connection.MongoConnection).ConnectionPool.lockConnection() [0x21f3ab1a]
??:? @safe vibe.core.connectionpool.LockedConnection!(vibe.db.mongo.connection.MongoConnection).LockedConnection vibe.db.mongo.client.MongoClient.lockConnection() [0x21f3a66e]
??:? @safe vibe.db.mongo.client.MongoClient vibe.db.mongo.client.MongoClient.__ctor(vibe.db.mongo.settings.MongoClientSettings) [0x21f3a467]
??:? @safe vibe.db.mongo.client.MongoClient vibe.db.mongo.mongo.connectMongoDB(vibe.db.mongo.settings.MongoClientSettings) [0x21f49b93]
??:? _Dmain [0x21ea15b1]
Program exited with code 1

```

**Comment by ohninedotseven** [comment]
well never mind. i fixed it by a: downgrading vibe.d to 0.7.32, then, changing two lines to check for integers instead of doubles for mongoconnection and now it works and it's able to interface with my mongodb server on azure
huh.
